Repository allegro/hermes, pull requests merged in 2022-10, with the labels that each got.

#1573 Fix automatic generation of release notes
  .github/workflows/release.yml
Labels: bug, hacktoberfest

#1575 Fix fragile float based ScoringTargetWeightCalculatorTest
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/workload/weighted/ScoringTargetWeightCalculatorTest.groovy
Labels: bug, hacktoberfest, flaky test

#1574 update docs
  docs/docs/quickstart.md
  docs/docs/user/java-client.md
  docs/docs/user/publishing.md
  docs/docs/user/subscribing.md
Labels: enhancement, hacktoberfest, documentation

#1567 Pubsub ability to not include additional headers
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/googlepubsub/GooglePubSubMetadataAppender.java
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/googlepubsub/GooglePubSubMessageSenderTest.groovy
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/googlepubsub/GooglePubSubMessagesTest.groovy
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/googlepubsub/GooglePubSubMetadataAppenderTest.groovy
Labels: enhancement, hacktoberfest

#1576 add ability to run integration tests on m1 mac
  build.gradle
  docs/docs/quickstart.md
  hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/ConfluentSchemaRegistryContainer.java
  hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/ImageTags.java
  hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/KafkaContainerCluster.java
  hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/ZookeeperContainer.java
  integration/build.gradle
Labels: enhancement, hacktoberfest

#1570 Restore assertion in OfflineRetransmissionManagementTest
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/OfflineRetransmissionManagementTest.java
Labels: bug

#1580 Remove deprecated max rate negotiation docs
  docs/docs/configuration/rate-limiting.md
Labels: enhancement, hacktoberfest

#1582 Replaced Gitter with GitHub discussions
  README.md
  ROADMAP.md
Labels: enhancement

#1585 Migrate to material theme
  docs/docs/index.md
  docs/theme/css/bootstrap/css/bootstrap-theme.min.css
  docs/theme/css/bootstrap/css/bootstrap.min.css
  docs/theme/css/bootstrap/fonts/glyphicons-halflings-regular.eot
  docs/theme/css/bootstrap/fonts/glyphicons-halflings-regular.svg
  docs/theme/css/bootstrap/fonts/glyphicons-halflings-regular.ttf
  docs/theme/css/bootstrap/fonts/glyphicons-halflings-regular.woff
  docs/theme/css/bootstrap/fonts/glyphicons-halflings-regular.woff2
  docs/theme/css/bootstrap/js/bootstrap.min.js
  docs/theme/css/font-awesome/css/font-awesome.min.css
  docs/theme/css/font-awesome/fonts/FontAwesome.otf
  docs/theme/css/font-awesome/fonts/fontawesome-webfont.eot
  docs/theme/css/font-awesome/fonts/fontawesome-webfont.svg
  docs/theme/css/font-awesome/fonts/fontawesome-webfont.ttf
  docs/theme/css/font-awesome/fonts/fontawesome-webfont.woff
  docs/theme/css/font-awesome/fonts/fontawesome-webfont.woff2
  docs/theme/css/highlight-default.css
  docs/theme/js/base.js
  docs/theme/js/highlight.min.js
  docs/theme/js/jquery-2.2.0.min.js
  docs/theme/main.html
  mkdocs.yml
  readthedocs.yml
  requirements.txt
Labels: enhancement

#1586 add support for confluent images > 5.x.x
  docker/.env
  docker/docker-compose.yml
  docs/docs/quickstart.md
Labels: enhancement, hacktoberfest

#1590 Add codeowners
  .github/CODEOWNERS
Labels: enhancement

#1587 Remove release hooks and version from console package.json
  build.gradle
  hermes-console/package.json
Labels: enhancement

#1594 Removed unnecessary feature flags
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/factories/MetricRegistryFactory.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/factories/MetricRegistryParameters.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/MetricRegistryWithExponentiallyDecayingReservoir.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/MetricsReservoirType.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/CommitOffsetProperties.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/ConsumerConfiguration.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/MetricsProperties.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetQueue.java
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetCommitterTest.groovy
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/result/DefaultErrorHandlerTest.groovy
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/result/DefaultSuccessHandlerTest.groovy
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/MetricsProperties.java
Labels: enhancement

#1572 End-to-end frontend tests
  .gitignore
  integration/README.md
  integration/build.gradle
  integration/src/integration/e2e/cypress.config.js
  integration/src/integration/e2e/cypress/e2e/groups.cy.js
  integration/src/integration/e2e/cypress/support/e2e.js
  integration/src/integration/e2e/cypress/support/generators.js
  integration/src/integration/e2e/package-lock.json
  integration/src/integration/e2e/package.json
  integration/src/integration/e2e/reporter-config.json
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/CypressTest.java
Labels: enhancement, hacktoberfest

#1597 register metadata-age and record-queue-time-max producer metrics
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Gauges.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/Producers.java
Labels: enhancement

#1593 #1433 Wait for readiness of all Zookeeper clusters
  integration/src/integration/java/pl/allegro/tech/hermes/integration/setup/HermesManagementInstance.java
Labels: bug

#1602 Fix checkstyle action
  .github/workflows/checkstyle.yml
  build.gradle
Labels: bug

#1579 Add option to skip events in hermes console
  hermes-console/static/js/console/subscription/SubscriptionController.js
  hermes-console/static/partials/modal/confirm.html
  hermes-console/static/partials/subscription.html
Labels: enhancement, hacktoberfest-accepted

#1589 Allow to reset selected received requests in Hermes Mock
  docs/docs/user/hermes-mock.md
  hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMock.java
  hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockQuery.java
  hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockRule.java
  hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/HermesMockTest.groovy
Labels: enhancement, hacktoberfest-accepted

#1604 resolve #1599 | checkstyle for unit tests
  .github/workflows/checkstyle.yml
  hermes-api/src/test/java/pl/allegro/tech/hermes/api/SubscriptionTest.java
  hermes-api/src/test/java/pl/allegro/tech/hermes/api/helper/PatchTest.java
  hermes-common/src/test/java/pl/allegro/tech/hermes/common/message/wrapper/AvroMessageContentWrapperTest.java
  hermes-common/src/test/java/pl/allegro/tech/hermes/common/message/wrapper/JsonMessageContentWrapperTest.java
  hermes-common/src/test/java/pl/allegro/tech/hermes/common/message/wrapper/MessageContentWrapperTest.java
  hermes-common/src/test/java/pl/allegro/tech/hermes/common/message/wrapper/SchemaAwareSerDeTest.java
  hermes-common/src/test/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/ZookeeperCounterStorageTest.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/batch/DirectBufferPoolTest.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/ByteBufferEntityTest.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyMessageSenderTest.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/sender/jms/JmsMessageSenderTest.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/sender/resolver/InterpolatingEndpointAddressResolverTest.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/ConsumerTestRuntimeEnvironment.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/WorkloadRegistryTest.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/WorkloadSupervisorIntegrationTest.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/weighted/ZookeeperConsumerNodeLoadRegistryTest.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/test/MessageBuilder.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/uri/UriUtilsTest.java
  hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/buffer/BackupFilesManagerTest.java
  hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/buffer/BackupMessagesLoaderTest.java
  hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/buffer/ChronicleMapMessageRepositoryTest.java
  hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaBrokerMessageProducerTest.java
  hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageContentTypeEnforcerTest.java
  hermes-mock/src/test/java/pl/allegro/tech/hermes/mock/HermesMockExtensionTest.java
  hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/management/ElasticsearchLogRepositoryTest.java
  hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/management/MultiElasticsearchLogRepositoryTest.java
  hermes-tracker/src/test/java/pl/allegro/tech/hermes/tracker/consumers/AbstractLogRepositoryTest.java
  hermes-tracker/src/test/java/pl/allegro/tech/hermes/tracker/consumers/TestMessageMetadata.java
  hermes-tracker/src/test/java/pl/allegro/tech/hermes/tracker/frontend/AbstractLogRepositoryTest.java
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1595 Hermes-frontend - metrics redesign
  docs/docs/deployment/metrics.md
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Gauges.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/HermesMetrics.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Timers.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/buffer/BackupMessagesLoader.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/metric/CachedTopic.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/Producers.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/MessageReadHandler.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/PublishingHandler.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageFactory.java
  hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/buffer/BackupMessagesLoaderTest.java
  hermes-tracker-elasticsearch/src/main/java/pl/allegro/tech/hermes/tracker/elasticsearch/metrics/Timers.java
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1611 Moved away from jcenter
  build.gradle
  integration/build.gradle
Labels: enhancement

#1610 resolve #1601 | Add checkstyle for benchmarks
  .github/workflows/checkstyle.yml
  hermes-benchmark/src/jmh/java/pl/allegro/tech/hermes/benchmark/HermesServerBenchmark.java
  hermes-benchmark/src/jmh/java/pl/allegro/tech/hermes/benchmark/MessageRepositoryBenchmark.java
  hermes-benchmark/src/jmh/java/pl/allegro/tech/hermes/benchmark/environment/BenchmarkMessageContentWrapper.java
  hermes-benchmark/src/jmh/java/pl/allegro/tech/hermes/benchmark/environment/HermesServerEnvironment.java
  hermes-benchmark/src/jmh/java/pl/allegro/tech/hermes/benchmark/environment/HermesServerFactory.java
  hermes-benchmark/src/jmh/java/pl/allegro/tech/hermes/benchmark/environment/InMemorySchemaClient.java
Labels: enhancement, hacktoberfest-accepted

#1609 Issue #1600 | Add checkstyle to integration tests
  .github/workflows/checkstyle.yml
  integration/src/integration/java/pl/allegro/tech/hermes/frontend/AuthConfiguration.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/AbstractFrontendShutdownTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/AsyncPublisherAutoRetryTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/AttachingKeepAliveHeaderTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/BatchDeliveryTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/BatchRetryPolicyTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/ConsumingHttp2Test.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/FilteringAvroTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/FilteringHeadersTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/FilteringJsonTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/GooglePubSubConsumingTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/HealthCheckTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/HermesClientPublishingHttpsTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/JmsConsumingTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/KafkaRetransmissionServiceTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/KafkaSingleMessageReaderTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/MessageBufferLoadingTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/MetricsTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/MultipleKafkaTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/OAuthIntegrationTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingAvroOnTopicWithoutSchemaTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingAvroTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/ReadinessCheckTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/TopicBlacklistTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/auth/FrontendAuthenticationConfigurationTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/auth/TopicAuthorisationTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/env/ConsumersStarter.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/env/FrontendStarter.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/env/HermesIntegrationEnvironment.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/env/SharedServices.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/helper/GraphiteEndpoint.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/helper/RemoteOAuthEndpoint.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/helper/Waiter.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/helper/graphite/GraphiteMockServer.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/CrowdOwnerSourceIntegrationTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/FiltersVerificationTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/GroupManagementTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/HealthCheckTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/ListClientsForTopicTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/ListSubscriptionForOwnerTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/ListUnhealthySubscriptionsForOwnerTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/OAuthProviderManagementTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/OfflineRetransmissionManagementTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/QueryEndpointTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/ReadOnlyModeTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SubscriptionManagementTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/TopicManagementTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/metadata/TraceHeadersPropagator.java
  integration/src/integration/java/pl/allegro/tech/hermes/management/TestSecurityProvider.java
Labels: enhancement, hacktoberfest-accepted
