Repository allegro/hermes, pull requests merged in 2023-03, with the labels that each got.

#1654 Fix hermes-mock avro content matching (#1653)
  hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/matching/AvroContentMatcher.java
  hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/HermesMockAvroTest.groovy
  hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/TestMessage.groovy
Labels: bug

#1655 hermes-mock - stub mappings remove support
  docs/docs/user/hermes-mock.md
  hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockDefine.java
  hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockHelper.java
  hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/HermesMockAvroTest.groovy
  hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/HermesMockJsonTest.groovy
Labels: enhancement

#1596 Reduce deprecated usages
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/OAuthProvider.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/OfflineRetransmissionRequest.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/Subscription.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicLabel.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicName.java
  hermes-client/src/main/java/pl/allegro/tech/hermes/client/restTemplate/RestTemplateHermesSender.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/oauth/client/OAuthTokenResponse.java
  hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/ConfluentSchemaRegistryContainer.java
  hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/KafkaContainer.java
  hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/ZookeeperContainer.java
  integration/build.gradle
  integration/src/integration/java/pl/allegro/tech/hermes/integration/AsyncPublisherAutoRetryTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/OfflineRetransmissionManagementTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/QueryEndpointTest.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SubscriptionManagementTest.java
Labels: enhancement, hacktoberfest-accepted

#1656 Improved support for multiple data centers in hermes-management
  hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperBasedRepository.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperCredentialsRepository.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperGroupRepository.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperOAuthProviderRepository.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionRepository.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperTopicRepository.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperWorkloadConstraintsRepository.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/counter/ZookeeperCounterException.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/storage/StorageConfiguration.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/metrics/SummedSharedCounter.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/readiness/ZookeeperDatacenterReadinessRepository.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/retransmit/ZookeeperOfflineRetransmissionRepository.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/zookeeper/ZookeeperClientManager.java
  hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/metrics/SummedSharedCounterTest.groovy
  hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/zookeeper/ZookeeperClientManagerTest.groovy
  hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/utils/MultiZookeeperIntegrationTest.groovy
  integration/src/integration/java/pl/allegro/tech/hermes/integration/env/HermesIntegrationEnvironment.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/setup/HermesManagementInstance.java
Labels: enhancement
