Repository allegro/hermes, pull requests merged in 2023-10, with the labels that each got.

#1744 Hermes console vue hotfix
  hermes-console-vue/src/components/console-footer/ConsoleFooter.vue
  hermes-console-vue/src/composables/topic/use-form-topic/parser.ts
  hermes-console-vue/src/i18n/en-US/index.ts
  hermes-console-vue/src/utils/copy-utils.ts
  hermes-console-vue/src/views/group-topics/group-topics-listing/GroupTopicsListing.vue
  hermes-console-vue/src/views/groups/group-listing/GroupListing.vue
  hermes-console-vue/src/views/topic/schema-panel/SchemaPanel.vue
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1743 Hermes console 2 | JSON auto formatting with code highlighting for AVRO schema.
  hermes-console-vue/package.json
  hermes-console-vue/src/config/ace-config.ts
  hermes-console-vue/src/i18n/en-US/index.ts
  hermes-console-vue/src/i18n/en-US/topic-form.ts
  hermes-console-vue/src/views/topic/topic-form/TopicForm.vue
  hermes-console-vue/yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1745 Hermes console vue subscription filters debug
  .github/workflows/ci-console.yml
  hermes-console-vue/src/components/ace-editor/AceEditor.vue
  hermes-console-vue/src/components/ace-editor/ace-config.ts
  hermes-console-vue/src/views/subscription/subscription-form/subscription-basic-filters/SubscriptionPathFiltersDebug.vue
  hermes-console-vue/src/views/topic/topic-form/TopicForm.vue
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1746 filtering subscription list in topic view
  hermes-console-vue/src/i18n/en-US/index.ts
  hermes-console-vue/src/views/topic/subscriptions-list/SubscriptionsList.vue
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1750 Added url to metrics dashboard
  hermes-console-vue/json-server/db.json
  hermes-console-vue/json-server/routes.json
  hermes-console-vue/src/api/app-configuration.ts
  hermes-console-vue/src/api/hermes-client/index.ts
  hermes-console-vue/src/components/key-value-card/KeyValueCard.vue
  hermes-console-vue/src/composables/metrics/use-metrics/useMetrics.spec.ts
  hermes-console-vue/src/composables/metrics/use-metrics/useMetrics.ts
  hermes-console-vue/src/dummy/app-config.ts
  hermes-console-vue/src/dummy/metricsDashboardUrl.ts
  hermes-console-vue/src/dummy/subscription.ts
  hermes-console-vue/src/i18n/en-US/index.ts
  hermes-console-vue/src/mocks/handlers.ts
  hermes-console-vue/src/utils/date-formatter/date-formatter.ts
  hermes-console-vue/src/views/subscription/SubscriptionView.spec.ts
  hermes-console-vue/src/views/subscription/SubscriptionView.vue
  hermes-console-vue/src/views/subscription/last-undelivered-message/LastUndeliveredMessage.spec.ts
  hermes-console-vue/src/views/subscription/last-undelivered-message/LastUndeliveredMessage.vue
  hermes-console-vue/src/views/subscription/metrics-card/MetricsCard.spec.ts
  hermes-console-vue/src/views/subscription/metrics-card/MetricsCard.vue
  hermes-console-vue/src/views/subscription/undelivered-messages-card/UndeliveredMessagesCard.spec.ts
  hermes-console-vue/src/views/subscription/undelivered-messages-card/UndeliveredMessagesCard.vue
  hermes-console-vue/src/views/topic/TopicView.spec.ts
  hermes-console-vue/src/views/topic/TopicView.vue
  hermes-console-vue/src/views/topic/metrics-list/MetricsList.spec.ts
  hermes-console-vue/src/views/topic/metrics-list/MetricsList.vue
  hermes-console-vue/src/views/topic/topic-header/TopicHeader.vue
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/MetricsDashboardUrlEndpoint.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/console/ConsoleProperties.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/MetricsDashboardUrl.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/MetricsDashboardUrlService.java
  hermes-management/src/main/resources/application-local.yaml
Labels: enhancement

#1723 Bring back optional dependencies
  build.gradle
  hermes-client/build.gradle
  hermes-frontend/build.gradle
  integration/build.gradle
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1753 Hermes console vue issue1751
  hermes-console-vue/src/components/key-value-card/key-value-card-item/KeyValueCardItem.vue
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1752 Anonymize password in subscription query
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/QueryEndpointTest.java
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1734 Add possibility of embedding cost report in hermes-console
  hermes-console/static/js/console/Home.js
  hermes-console/static/js/console/subscription/SubscriptionController.js
  hermes-console/static/js/console/topic/TopicController.js
  hermes-console/static/partials/home.html
  hermes-console/static/partials/subscription.html
  hermes-console/static/partials/topic.html
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/console/ConsoleProperties.java
Labels: enhancement

#1757 Avro pretty format view component.
  hermes-console-vue/src/i18n/en-US/index.ts
  hermes-console-vue/src/views/topic/schema-panel/AvroTypes.ts
  hermes-console-vue/src/views/topic/schema-panel/SchemaPanel.spec.ts
  hermes-console-vue/src/views/topic/schema-panel/SchemaPanel.vue
  hermes-console-vue/src/views/topic/schema-panel/avro-viewer/AvroNode.vue
  hermes-console-vue/src/views/topic/schema-panel/avro-viewer/AvroViewer.vue
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1747 Allow additional queries for prometheus external metrics
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/ExternalMonitoringConfiguration.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/PrometheusMonitoringClientProperties.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/prometheus/VictoriaMetricsMetricsProvider.java
  hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/metrics/HybridPrometheusBasedSubscriptionMetricsRepositoryTest.groovy
  hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/metrics/HybridPrometheusBasedTopicMetricsRepositoryTest.groovy
Labels: enhancement

#1759 support for editing boolean endpoint address resolver metadata properties
  hermes-console-vue/json-server/db.json
  hermes-console-vue/json-server/subscriptions.json
  hermes-console-vue/src/composables/subscription/use-create-subscription/useCreateSubscription.ts
  hermes-console-vue/src/composables/subscription/use-form-subscription/form-mapper.ts
  hermes-console-vue/src/composables/subscription/use-form-subscription/types.ts
  hermes-console-vue/src/composables/subscription/use-form-subscription/useFormSubscription.ts
  hermes-console-vue/src/dummy/subscription-form.ts
  hermes-console-vue/src/dummy/subscription.ts
  hermes-console-vue/src/views/subscription/properties-card/PropertiesCard.spec.ts
  hermes-console-vue/src/views/subscription/properties-card/PropertiesCard.vue
  hermes-console-vue/src/views/subscription/subscription-form/SubscriptionForm.vue
Labels: enhancement

#1733 check topic existence before listings its subscriptions
  .github/workflows/checkstyle.yml
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/Stats.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionStats.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicStats.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionRepository.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/MetricsDashboardUrl.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/consistency/DcConsistencyService.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/console/FrontendRoutesFilter.java
  integration/src/integration/java/pl/allegro/tech/hermes/integration/management/StatsTest.java
Labels: bug
