Repository allegro/hermes, pull requests merged in 2024-11, with the labels that each got.

#1915 Show AVRO pretty display for nullable array elements
  hermes-console/src/views/topic/schema-panel/avro-viewer/AvroNode.vue
Labels: bug, hacktoberfest

#1917 Avro path schema autocomplete input.
  hermes-console/src/utils/json-avro/avroTypes.ts
  hermes-console/src/utils/json-avro/jsonAvroUtils.spec.ts
  hermes-console/src/utils/json-avro/jsonAvroUtils.ts
  hermes-console/src/utils/json-avro/jsonUtils.spec.ts
  hermes-console/src/utils/json-avro/jsonUtils.ts
  hermes-console/src/views/subscription/SubscriptionView.vue
  hermes-console/src/views/subscription/filters-card/FiltersCard.vue
  hermes-console/src/views/subscription/subscription-form/SubscriptionForm.vue
  hermes-console/src/views/subscription/subscription-form/subscription-basic-filters/SubscriptionPathFilters.vue
  hermes-console/src/views/subscription/subscription-form/subscription-basic-filters/SubscriptionPathFiltersDebug.vue
  hermes-console/src/views/subscription/subscription-form/subscription-basic-filters/path-filter-row/PathFilterRow.vue
  hermes-console/src/views/subscription/subscription-metadata/SubscriptionMetadata.vue
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1910 Rewrite deprecated curator API - transactions
  hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperBasedRepository.java
  hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/cache/HierarchicalCacheTest.groovy
Labels: enhancement, hacktoberfest

#1913 #1905 | Added reason field to subscription/topic constraints
  docs/docs/configuration/consumers-tuning.md
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/Constraints.java
  hermes-api/src/test/groovy/pl/allegro/tech/hermes/api/SubscriptionConstraintsValidationTest.groovy
  hermes-api/src/test/groovy/pl/allegro/tech/hermes/api/TopicConstraintsValidationTest.groovy
  hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperWorkloadConstraintsCacheTest.groovy
  hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperWorkloadConstraintsRepositoryTest.groovy
  hermes-console/src/api/constraints.ts
  hermes-console/src/composables/constraints/use-constraints/useConstraints.spec.ts
  hermes-console/src/dummy/constraints.ts
  hermes-console/src/i18n/en-US/index.ts
  hermes-console/src/views/admin/constraints/create-constraint-form/CreateConstraintFormView.spec.ts
  hermes-console/src/views/admin/constraints/create-constraint-form/CreateConstraintFormView.vue
  hermes-console/src/views/admin/constraints/edit-constraint-form/EditConstraintFormView.vue
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/workload/WorkloadConstraintsTest.groovy
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/workload/weighted/WeightedWorkBalancerTest.groovy
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SelectiveWorkBalancerTest.java
  hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/workload/constraints/WorkloadConstraintsServiceTest.groovy
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1924 Make google-java-format works for forks
  .github/workflows/google-java-format.yml
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/Constraints.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperBasedRepository.java
Labels: bug

#1916 Improve timerange validation for retransmission from view
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/OfflineRetransmissionFromTopicRequest.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/OfflineRetransmissionFromViewRequest.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/OfflineRetransmissionRequest.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/OfflineRetransmissionTask.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/constraints/OneSourceRetransmissionValidator.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/constraints/TimeRangeForTopicRetransmission.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/constraints/TimeRangeForTopicRetransmissionValidator.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/jackson/OptionalInstantIsoSerializer.java
  hermes-api/src/test/groovy/pl/allegro/tech/hermes/api/constraints/OneSourceRetransmissionValidatorTest.groovy
  hermes-api/src/test/groovy/pl/allegro/tech/hermes/api/constraints/RetransmissionTimeRangeValidatorTest.groovy
  hermes-console/json-server/db.json
  hermes-console/src/api/app-configuration.ts
  hermes-console/src/api/offline-retransmission.ts
  hermes-console/src/dummy/app-config.ts
  hermes-console/src/i18n/en-US/index.ts
  hermes-console/src/views/topic/offline-retransmission/OfflineRetransmissionForm.spec.ts
  hermes-console/src/views/topic/offline-retransmission/OfflineRetransmissionForm.vue
  hermes-console/src/views/topic/topic-header/TopicHeader.vue
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/OfflineRetransmissionEndpoint.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/console/ConsoleProperties.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/retransmit/OfflineRetransmissionService.java
  hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/client/integration/HermesTestClient.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/OfflineRetransmissionManagementTest.java
Labels: enhancement, cleanup

#1919 resolve #1912 | Add buttons for switching between different environments
  hermes-console/json-server/db.json
  hermes-console/src/api/app-configuration.ts
  hermes-console/src/components/console-header/ConsoleHeader.vue
  hermes-console/src/components/environment-switch/EnvironmentSwitch.spec.ts
  hermes-console/src/components/environment-switch/EnvironmentSwitch.vue
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/console/ConsoleProperties.java
  hermes-management/src/main/resources/application-local.yaml
  hermes-management/src/main/resources/console/config-local.json
Labels: enhancement, hacktoberfest

#1930 Updated prometheus version
  build.gradle
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/factories/PrometheusMeterRegistryFactory.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/CommonConfiguration.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/PrometheusConfigAdapter.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/ServerConfiguration.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/server/ConsumerHttpServer.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/CommonConfiguration.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/FrontendServerConfiguration.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/PrometheusConfigAdapter.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/HermesServer.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/PrometheusMetricsHandler.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/PrometheusConfigAdapter.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/PrometheusConfiguration.java
Labels: bug
