Repository allegro/hermes, pull requests merged in 2024-06, with the labels that each got.

#1866 Improve ACK docs
  docs/docs/configuration/buffer-persistence.md
  docs/docs/user/publishing.md
  hermes-console/src/components/console-alert/ConsoleAlert.vue
  hermes-console/src/composables/topic/use-create-topic/useCreateTopic.ts
  hermes-console/src/composables/topic/use-form-topic/types.ts
  hermes-console/src/composables/topic/use-form-topic/useFormTopic.ts
  hermes-console/src/dummy/topic-form.ts
  hermes-console/src/i18n/en-US/index.ts
  hermes-console/src/i18n/en-US/topic-form.ts
  hermes-console/src/views/topic/topic-form/TopicForm.vue
Labels: enhancement, documentation

#1868 transition to error state upon failing publishing handler
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/PublishingHandler.java
Labels: bug

#1870 make message thread safe
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/Message.java
Labels: bug

#1869 Added measurement point to consumer profiling
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/profiling/Measurement.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/ConsumerProfilingTest.java
Labels: enhancement

#1872 Downgrade kafka clients
  build.gradle
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaMessageSender.java
Labels: bug

#1874 InflightSize and retentionTime validation improvements
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/RetentionTime.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionPolicy.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/validator/SubscriptionValidator.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidator.java
  hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/subscription/validator/InflightSizeValidatorTest.groovy
  hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidatorWithRealApiPreconditionsTest.groovy
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/SubscriptionManagementTest.java
Labels: enhancement

#1871 Fix topic search redirect link
  hermes-console/src/views/search/topic-search-results/TopicSearchResults.vue
Labels: bug

#1876 Allow for 'empty' broadcast send attempt
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/Message.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyBroadCastMessageSender.java
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyBroadCastMessageSenderTest.groovy
Labels: bug, enhancement
