Repository allegro/hermes, pull requests merged in 2024-01, with the labels that each got.

#1810 Update GH Actions, adjust Gradle cache
  .github/workflows/checkstyle.yml
  .github/workflows/ci-console.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/markdown-links-check.yml
  .github/workflows/release.yml
  .github/workflows/test_report.yml
Labels: enhancement

#1815 Fixed shouldQueryTopicsMetrics test
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/QueryEndpointTest.java
Labels: enhancement, flaky test

#1813 Upgrade spring boot to 3.2.1
  build.gradle
  hermes-client/build.gradle
  hermes-consumers/build.gradle
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/ConsumerSenderConfiguration.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/oauth/client/OAuthHttpClient.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/MessageSendingResult.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/SingleMessageSendingResult.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/BatchHttpRequestFactory.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/DefaultBatchHttpRequestFactory.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/DefaultHttpMetadataAppender.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/DefaultHttpRequestFactory.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/DefaultHttpRequestFactoryProvider.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/DefaultSendingResultHandlers.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpClientsFactory.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpClientsWorkloadReporter.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpRequestFactory.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpRequestFactoryProvider.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyBroadCastMessageSender.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyBroadCastResponseListener.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyHttpMessageSenderProvider.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyMessageBatchSender.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyMessageSender.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyResponseListener.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/SendingResultHandlers.java
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpClientsWorkloadReporterTest.groovy
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyBroadCastMessageSenderTest.groovy
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/console/ConsoleConfiguration.java
  hermes-mock/build.gradle
  hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockDefine.java
  hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockQuery.java
  hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/exchange/Response.java
  hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/matching/StartsWithPattern.java
Labels: enhancement

#1811 add missing docs for subscription options
  docs/docs/user/publishing.md
  docs/docs/user/subscribing.md
Labels: enhancement, documentation

#1817 allow tasks to be rejected
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/BrokerLatencyReporter.java
Labels: enhancement

#1818 Improving tests stability, minor code fixes
  .github/workflows/ci.yml
  hermes-management/src/main/resources/application.yaml
  integration-tests/src/common/java/pl/allegro/tech/hermes/frontend/FrontendConfigurationProperties.java
  integration-tests/src/common/java/pl/allegro/tech/hermes/integrationtests/setup/HermesExtension.java
  integration-tests/src/common/java/pl/allegro/tech/hermes/integrationtests/setup/HermesManagementTestApp.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/PublishingAvroTest.java
  integration-tests/src/slowIntegrationTest/java/pl/allegro/tech/hermes/integrationtests/TopicCreationRollbackTest.java
  settings.gradle
Labels: enhancement

#1819 Fixed checkstyle
  config/checkstyle/checkstyle.xml
  integration-tests/src/common/java/pl/allegro/tech/hermes/integrationtests/setup/HermesExtension.java
  integration-tests/src/common/java/pl/allegro/tech/hermes/integrationtests/subscriber/TestJmsSubscriber.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/BatchRetryPolicyTest.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/JmsConsumingTest.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/KafkaRetransmissionServiceTest.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/KafkaSingleMessageReaderTest.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/MetricsTest.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/PublishingAndConsumingTest.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/PublishingAvroTest.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/ReadinessCheckTest.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/UndeliveredLogTest.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/QueryEndpointTest.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/TopicManagementTest.java
  integration-tests/src/slowIntegrationTest/java/pl/allegro/tech/hermes/integrationtests/AttachingKeepAliveHeaderTest.java
  integration-tests/src/slowIntegrationTest/java/pl/allegro/tech/hermes/integrationtests/HermesServerGracefulShutdownTest.java
  integration-tests/src/slowIntegrationTest/java/pl/allegro/tech/hermes/integrationtests/KafkaReadinessCheckTest.java
  integration-tests/src/slowIntegrationTest/java/pl/allegro/tech/hermes/integrationtests/MessageBufferLoadingTest.java
  integration-tests/src/slowIntegrationTest/java/pl/allegro/tech/hermes/integrationtests/MultiDatacenterPublishingAndSubscribingTest.java
  integration-tests/src/slowIntegrationTest/java/pl/allegro/tech/hermes/integrationtests/PublishingAvroOnTopicWithoutSchemaTest.java
  integration-tests/src/slowIntegrationTest/java/pl/allegro/tech/hermes/integrationtests/TopicCreationRollbackTest.java
Labels: enhancement

#1809 fix date parser in OfflineRetransmissionRequest class
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/OfflineRetransmissionRequest.java
Labels: bug
