Repository allegro/hermes, pull requests merged in 2024-07, with the labels that each got.

#1875 allow configuration of default value for remoteDatacenterFallbackEnabled
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/Topic.java
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicWithSchema.java
  hermes-api/src/test/java/pl/allegro/tech/hermes/api/TopicTest.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/factories/ObjectMapperFactory.java
  hermes-common/src/test/groovy/pl/allegro/tech/hermes/test/IntegrationTest.groovy
  hermes-common/src/test/java/pl/allegro/tech/hermes/common/di/ObjectMapperFactoryTest.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/CommonConfiguration.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/CommonConfiguration.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/TopicDefaultsProperties.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/ManagementConfiguration.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/TopicProperties.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java
Labels: enhancement

#1877 Revert accidental "improve fallback to remote dc validation"
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidator.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/TopicManagementTest.java
Labels: bug

#1878 Improved topic validation
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidator.java
  hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidatorTest.groovy
  hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidatorWithRealApiPreconditionsTest.groovy
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/TopicManagementTest.java
Labels: enhancement

#1880 Add docs about message duplication
  docs/docs/user/publishing.md
  docs/docs/user/subscribing.md
Labels: enhancement, documentation

#1862 New offset committing
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Gauges.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/SubscriptionMetrics.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/ConsumerConfiguration.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/ConsumerReceiverConfiguration.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/SupervisorConfiguration.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/BatchConsumer.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderFactory.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/filtering/FilteredMessageHandler.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/MessageState.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetCommitter.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetQueue.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetsToCommit.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/PendingOffsets.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/PendingOffsetsAppender.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/SubscriptionPartitionOffset.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/MessageCommitter.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/ReceiverFactory.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiverFactory.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/result/DefaultErrorHandler.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/result/DefaultSuccessHandler.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/ConsumerFactory.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/NonblockingConsumersSupervisor.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcess.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessSupervisor.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/Signal.java
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetCommitterTest.groovy
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetCommitterTestHelper.groovy
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/offset/PendingOffsetsTest.groovy
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/result/DefaultErrorHandlerTest.groovy
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/result/DefaultSuccessHandlerTest.groovy
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessSupervisorTest.groovy
  hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/process/SignalsFilterTest.groovy
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java
  hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/ConsumerTestRuntimeEnvironment.java
  hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/client/integration/HermesTestClient.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/KafkaRetransmissionServiceTest.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/PublishingAvroTest.java
Labels: enhancement
