Repository allegro/hermes, pull requests merged in 2025-08, with the labels that each got.

#1971 Revert "GH-1808 | Logical type decimal to json as string (#1957)"
  build.gradle
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/message/converter/AvroBinaryDecoders.java
  hermes-common/src/main/java/pl/allegro/tech/hermes/common/message/converter/AvroRecordToBytesConverter.java
  hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/converter/AvroToJsonMessageConverter.java
  hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageToJsonConverter.java
  hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/publishing/message/MessageToJsonConverterTest.groovy
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/AvroConfiguration.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/kafka/KafkaConfiguration.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/service/KafkaSingleMessageReader.java
  hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockHelper.java
  hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/avro/AvroUser.java
  hermes-test-helper/src/main/resources/schema/user_4.avsc
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/PublishingAvroTest.java
Labels: bug

#1959 Active offline retransmissions view
  hermes-api/src/main/java/pl/allegro/tech/hermes/api/OfflineRetransmissionTaskMonitoringInfo.java
  hermes-console/json-server/active-offline-retransmission-tasks.json
  hermes-console/json-server/db.json
  hermes-console/json-server/server.ts
  hermes-console/src/api/app-configuration.ts
  hermes-console/src/api/hermes-client/index.ts
  hermes-console/src/api/offline-retransmission.ts
  hermes-console/src/composables/topic/use-offline-retransmission/useOfflineRetransmission.ts
  hermes-console/src/composables/topic/use-topic/useTopic.spec.ts
  hermes-console/src/composables/topic/use-topic/useTopic.ts
  hermes-console/src/dummy/app-config.ts
  hermes-console/src/dummy/topic.ts
  hermes-console/src/i18n/en-US/index.ts
  hermes-console/src/mocks/handlers.ts
  hermes-console/src/views/topic/TopicView.spec.ts
  hermes-console/src/views/topic/TopicView.vue
  hermes-console/src/views/topic/offline-retransmission/OfflineRetransmissionForm.vue
  hermes-console/src/views/topic/offline-retransmission/OfflineRetransmissionInfo.spec.ts
  hermes-console/src/views/topic/offline-retransmission/OfflineRetransmissionInfo.vue
  hermes-console/src/views/topic/topic-header/TopicHeader.spec.ts
  hermes-console/src/views/topic/topic-header/TopicHeader.vue
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/OfflineRetransmissionEndpoint.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/OfflineRetransmissionConfiguration.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/console/ConsoleProperties.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/retransmit/DefaultRetransmissionMonitoringUrlProvider.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/retransmit/OfflineRetransmissionService.java
  hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/retransmit/RetransmissionMonitoringUrlProvider.java
  hermes-management/src/main/resources/application-local.yaml
  hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/client/integration/HermesTestClient.java
  hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/client/integration/ManagementTestClient.java
  integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/OfflineRetransmissionManagementTest.java
Labels: enhancement

#1911 resolve #1907 | handle record references when presenting avro schema
  hermes-console/json-server/db.json
  hermes-console/json-server/topics.json
  hermes-console/src/dummy/topic.ts
  hermes-console/src/views/topic/schema-panel/AvroTypes.ts
  hermes-console/src/views/topic/schema-panel/avro-viewer/AvroNode.vue
  hermes-console/src/views/topic/schema-panel/avro-viewer/AvroViewer.vue
  hermes-console/src/views/topic/schema-panel/avro-viewer/avro-record-types-registry.spec.ts
  hermes-console/src/views/topic/schema-panel/avro-viewer/avro-record-types-registry.ts
Labels: enhancement, hacktoberfest

#1975 Revert "Debug subscription filters fix (#1967)"
  hermes-console/src/views/subscription/subscription-form/subscription-basic-filters/path-filter-row/PathFilterRow.vue
  hermes-console/src/views/subscription/subscription-form/subscription-header-filters/SubscriptionHeaderFilters.vue
  hermes-console/src/views/subscription/subscription-form/subscription-header-filters/header-filter-row/HeaderFilterRow.vue
Labels: bug

#1977 Fix filters in subscription form
  hermes-console/src/api/subscription.ts
  hermes-console/src/composables/subscription/use-edit-subscription/useEditSubscription.spec.ts
  hermes-console/src/composables/subscription/use-form-subscription/form-mapper.ts
  hermes-console/src/composables/subscription/use-form-subscription/useFormSubscription.ts
  hermes-console/src/dummy/subscription-form.ts
  hermes-console/src/views/subscription/subscription-form/subscription-basic-filters/path-filter-row/PathFilterRow.vue
  hermes-console/src/views/subscription/subscription-form/subscription-header-filters/SubscriptionHeaderFilters.vue
  hermes-console/src/views/subscription/subscription-form/subscription-header-filters/header-filter-row/HeaderFilterRow.vue
  hermes-console/src/views/subscription/subscription-form/subscription-header-filters/types.ts
Labels: bug
